-- Mission Control Database Schema
-- PostgreSQL 14+
-- Version: 1.0.0

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================================================
-- INVENTORY TABLES
-- =============================================================================

-- Hosts (physical/virtual machines, K8s nodes, containers)
CREATE TABLE hosts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL CHECK (type IN (
        'proxmox-node', 'vm', 'k8s-node', 'docker-host', 'lxc-container'
    )),
    cluster VARCHAR(255),
    addresses JSONB NOT NULL DEFAULT '{}',
    status VARCHAR(50) NOT NULL DEFAULT 'unknown' CHECK (status IN (
        'online', 'offline', 'degraded', 'unknown'
    )),
    last_seen_at TIMESTAMPTZ,
    tags TEXT[] DEFAULT '{}',
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(name, cluster)
);

-- Workloads (deployments, pods, VMs, LXCs, containers)
CREATE TABLE workloads (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL CHECK (type IN (
        'k8s-deployment', 'k8s-statefulset', 'k8s-pod', 'k8s-daemonset',
        'proxmox-vm', 'proxmox-lxc', 'docker-container', 'compose-stack'
    )),
    host_id UUID REFERENCES hosts(id) ON DELETE SET NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'unknown' CHECK (status IN (
        'running', 'stopped', 'pending', 'failed', 'unknown'
    )),
    namespace VARCHAR(255),
    spec JSONB NOT NULL DEFAULT '{}',
    health_status VARCHAR(50) DEFAULT 'unknown' CHECK (health_status IN (
        'healthy', 'unhealthy', 'unknown'
    )),
    last_updated_at TIMESTAMPTZ,
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Services (logical groupings of workloads)
CREATE TABLE services (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    owner VARCHAR(255),
    workload_ids UUID[] DEFAULT '{}',
    urls TEXT[] DEFAULT '{}',
    slo_targets JSONB DEFAULT '{}',
    runbook_url TEXT,
    tags TEXT[] DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- TASK & RUN TABLES
-- =============================================================================

-- Tasks (templates or one-off task definitions)
CREATE TABLE tasks (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title VARCHAR(500) NOT NULL,
    description TEXT,
    created_by VARCHAR(255) NOT NULL,
    is_template BOOLEAN NOT NULL DEFAULT false,
    tags TEXT[] DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Task Runs (execution instances)
CREATE TABLE task_runs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    task_id UUID REFERENCES tasks(id) ON DELETE SET NULL,
    user_prompt TEXT NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'queued' CHECK (status IN (
        'queued', 'planning', 'awaiting_approval', 'executing',
        'paused', 'succeeded', 'failed', 'canceled'
    )),
    result TEXT,
    approved_at TIMESTAMPTZ,
    approved_by VARCHAR(255),
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    started_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ
);

-- Task Events (append-only log of events during task execution)
CREATE TABLE task_events (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    run_id UUID NOT NULL REFERENCES task_runs(id) ON DELETE CASCADE,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    type VARCHAR(100) NOT NULL CHECK (type IN (
        'log', 'tool_call', 'tool_result', 'llm_request', 'llm_response',
        'approval_required', 'status_change', 'artifact', 'error'
    )),
    data JSONB NOT NULL DEFAULT '{}',
    metadata JSONB DEFAULT '{}'
);

-- Artifacts (files, outputs, links generated by tasks)
CREATE TABLE artifacts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    run_id UUID NOT NULL REFERENCES task_runs(id) ON DELETE CASCADE,
    type VARCHAR(50) NOT NULL CHECK (type IN (
        'text', 'json', 'markdown', 'file', 'link', 'image'
    )),
    uri TEXT NOT NULL,
    label VARCHAR(500),
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- LLM USAGE & COST TRACKING
-- =============================================================================

-- LLM Requests
CREATE TABLE llm_requests (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    run_id UUID NOT NULL REFERENCES task_runs(id) ON DELETE CASCADE,
    provider VARCHAR(50) NOT NULL CHECK (provider IN (
        'ollama', 'claude', 'gemini', 'openai', 'github-models'
    )),
    model VARCHAR(100) NOT NULL,
    tools_included BOOLEAN NOT NULL DEFAULT false,
    tool_schema_bytes INTEGER DEFAULT 0,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    duration_ms INTEGER
);

-- LLM Responses
CREATE TABLE llm_responses (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    request_id UUID NOT NULL REFERENCES llm_requests(id) ON DELETE CASCADE,
    finish_reason VARCHAR(50) CHECK (finish_reason IN (
        'stop', 'tool_calls', 'length', 'error', 'unknown'
    )),
    output_bytes INTEGER DEFAULT 0,
    duration_ms INTEGER,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Token Usage (denormalized for easy aggregation)
CREATE TABLE token_usage (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    request_id UUID NOT NULL REFERENCES llm_requests(id) ON DELETE CASCADE,
    run_id UUID NOT NULL REFERENCES task_runs(id) ON DELETE CASCADE,
    provider VARCHAR(50) NOT NULL,
    model VARCHAR(100) NOT NULL,
    input_tokens INTEGER NOT NULL DEFAULT 0,
    output_tokens INTEGER NOT NULL DEFAULT 0,
    total_tokens INTEGER GENERATED ALWAYS AS (input_tokens + output_tokens) STORED,
    estimated_cost_usd DECIMAL(10, 6) DEFAULT 0.00,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    metadata JSONB DEFAULT '{}'
);

-- Provider Pricing Config (static pricing table)
CREATE TABLE provider_pricing (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    provider VARCHAR(50) NOT NULL,
    model VARCHAR(100) NOT NULL,
    input_token_price DECIMAL(12, 8) NOT NULL,  -- per 1M tokens
    output_token_price DECIMAL(12, 8) NOT NULL, -- per 1M tokens
    active_since DATE NOT NULL,
    active_until DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(provider, model, active_since)
);

-- =============================================================================
-- TOOLS & POLICIES
-- =============================================================================

-- Tool Definitions
CREATE TABLE tool_definitions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT NOT NULL,
    risk_level VARCHAR(50) NOT NULL CHECK (risk_level IN (
        'READ_ONLY', 'SAFE_MUTATE', 'DESTRUCTIVE'
    )),
    requires_approval BOOLEAN NOT NULL DEFAULT false,
    json_schema JSONB NOT NULL,
    tags TEXT[] DEFAULT '{}',
    connector_id VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Tool Call Records
CREATE TABLE tool_call_records (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    run_id UUID NOT NULL REFERENCES task_runs(id) ON DELETE CASCADE,
    tool_id UUID REFERENCES tool_definitions(id) ON DELETE SET NULL,
    tool_name VARCHAR(255) NOT NULL,
    args JSONB NOT NULL DEFAULT '{}',
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ended_at TIMESTAMPTZ,
    success BOOLEAN,
    result_size INTEGER DEFAULT 0,
    error_message TEXT,
    metadata JSONB DEFAULT '{}'
);

-- Policies
CREATE TABLE policies (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    rules JSONB NOT NULL DEFAULT '[]',
    active_from TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    active_to TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- AUDIT LOG
-- =============================================================================

-- Audit Entries (append-only, immutable)
CREATE TABLE audit_entries (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actor JSONB NOT NULL,
    action VARCHAR(100) NOT NULL,
    resource_type VARCHAR(100) NOT NULL,
    resource_id UUID,
    changes JSONB,
    outcome VARCHAR(50) NOT NULL CHECK (outcome IN ('success', 'failure')),
    reason TEXT,
    metadata JSONB DEFAULT '{}'
);

-- =============================================================================
-- INDEXES
-- =============================================================================

-- Hosts
CREATE INDEX idx_hosts_type ON hosts(type);
CREATE INDEX idx_hosts_status ON hosts(status);
CREATE INDEX idx_hosts_cluster ON hosts(cluster);
CREATE INDEX idx_hosts_tags ON hosts USING GIN(tags);

-- Workloads
CREATE INDEX idx_workloads_type ON workloads(type);
CREATE INDEX idx_workloads_status ON workloads(status);
CREATE INDEX idx_workloads_namespace ON workloads(namespace);
CREATE INDEX idx_workloads_host_id ON workloads(host_id);
CREATE INDEX idx_workloads_health_status ON workloads(health_status);

-- Services
CREATE INDEX idx_services_name ON services(name);
CREATE INDEX idx_services_owner ON services(owner);
CREATE INDEX idx_services_tags ON services USING GIN(tags);

-- Tasks
CREATE INDEX idx_tasks_created_by ON tasks(created_by);
CREATE INDEX idx_tasks_is_template ON tasks(is_template);
CREATE INDEX idx_tasks_created_at ON tasks(created_at DESC);
CREATE INDEX idx_tasks_tags ON tasks USING GIN(tags);

-- Task Runs
CREATE INDEX idx_task_runs_task_id ON task_runs(task_id);
CREATE INDEX idx_task_runs_status ON task_runs(status);
CREATE INDEX idx_task_runs_created_at ON task_runs(created_at DESC);
CREATE INDEX idx_task_runs_task_created ON task_runs(task_id, created_at DESC);

-- Task Events
CREATE INDEX idx_task_events_run_id ON task_events(run_id);
CREATE INDEX idx_task_events_timestamp ON task_events(timestamp DESC);
CREATE INDEX idx_task_events_type ON task_events(type);
CREATE INDEX idx_task_events_run_timestamp ON task_events(run_id, timestamp DESC);

-- Artifacts
CREATE INDEX idx_artifacts_run_id ON artifacts(run_id);
CREATE INDEX idx_artifacts_type ON artifacts(type);

-- LLM Requests
CREATE INDEX idx_llm_requests_run_id ON llm_requests(run_id);
CREATE INDEX idx_llm_requests_provider ON llm_requests(provider);
CREATE INDEX idx_llm_requests_started_at ON llm_requests(started_at DESC);

-- Token Usage
CREATE INDEX idx_token_usage_run_id ON token_usage(run_id);
CREATE INDEX idx_token_usage_request_id ON token_usage(request_id);
CREATE INDEX idx_token_usage_provider ON token_usage(provider);
CREATE INDEX idx_token_usage_model ON token_usage(model);
CREATE INDEX idx_token_usage_recorded_at ON token_usage(recorded_at DESC);
CREATE INDEX idx_token_usage_provider_recorded ON token_usage(provider, recorded_at DESC);

-- Provider Pricing
CREATE INDEX idx_provider_pricing_provider_model ON provider_pricing(provider, model);
CREATE INDEX idx_provider_pricing_active ON provider_pricing(active_since, active_until);

-- Tool Definitions
CREATE INDEX idx_tool_definitions_name ON tool_definitions(name);
CREATE INDEX idx_tool_definitions_risk_level ON tool_definitions(risk_level);
CREATE INDEX idx_tool_definitions_tags ON tool_definitions USING GIN(tags);

-- Tool Call Records
CREATE INDEX idx_tool_call_records_run_id ON tool_call_records(run_id);
CREATE INDEX idx_tool_call_records_tool_id ON tool_call_records(tool_id);
CREATE INDEX idx_tool_call_records_started_at ON tool_call_records(started_at DESC);

-- Policies
CREATE INDEX idx_policies_active ON policies(active_from, active_to);

-- Audit Entries
CREATE INDEX idx_audit_entries_timestamp ON audit_entries(timestamp DESC);
CREATE INDEX idx_audit_entries_action ON audit_entries(action);
CREATE INDEX idx_audit_entries_resource_type ON audit_entries(resource_type);
CREATE INDEX idx_audit_entries_resource_id ON audit_entries(resource_id);
CREATE INDEX idx_audit_entries_outcome ON audit_entries(outcome);

-- =============================================================================
-- TRIGGERS (auto-update timestamps)
-- =============================================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_hosts_updated_at
    BEFORE UPDATE ON hosts
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_workloads_updated_at
    BEFORE UPDATE ON workloads
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_services_updated_at
    BEFORE UPDATE ON services
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_tasks_updated_at
    BEFORE UPDATE ON tasks
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_tool_definitions_updated_at
    BEFORE UPDATE ON tool_definitions
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_policies_updated_at
    BEFORE UPDATE ON policies
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- =============================================================================
-- SEED DATA (default pricing for common providers)
-- =============================================================================

-- Ollama (local, free)
INSERT INTO provider_pricing (provider, model, input_token_price, output_token_price, active_since)
VALUES ('ollama', 'mistral', 0.00, 0.00, '2024-01-01');

INSERT INTO provider_pricing (provider, model, input_token_price, output_token_price, active_since)
VALUES ('ollama', 'llama2', 0.00, 0.00, '2024-01-01');

-- Gemini (free tier pricing estimates)
INSERT INTO provider_pricing (provider, model, input_token_price, output_token_price, active_since)
VALUES ('gemini', 'gemini-2.0-flash-exp', 0.00, 0.00, '2024-01-01');

INSERT INTO provider_pricing (provider, model, input_token_price, output_token_price, active_since)
VALUES ('gemini', 'gemini-pro', 0.50, 1.50, '2024-01-01');

-- Claude (Anthropic pricing as of 2024)
INSERT INTO provider_pricing (provider, model, input_token_price, output_token_price, active_since)
VALUES ('claude', 'claude-3-sonnet-20240229', 3.00, 15.00, '2024-02-01');

INSERT INTO provider_pricing (provider, model, input_token_price, output_token_price, active_since)
VALUES ('claude', 'claude-3-opus-20240229', 15.00, 75.00, '2024-02-01');

INSERT INTO provider_pricing (provider, model, input_token_price, output_token_price, active_since)
VALUES ('claude', 'claude-3-haiku-20240307', 0.25, 1.25, '2024-03-01');

-- OpenAI (pricing as of 2024)
INSERT INTO provider_pricing (provider, model, input_token_price, output_token_price, active_since)
VALUES ('openai', 'gpt-4-turbo', 10.00, 30.00, '2024-01-01');

INSERT INTO provider_pricing (provider, model, input_token_price, output_token_price, active_since)
VALUES ('openai', 'gpt-4', 30.00, 60.00, '2024-01-01');

INSERT INTO provider_pricing (provider, model, input_token_price, output_token_price, active_since)
VALUES ('openai', 'gpt-3.5-turbo', 0.50, 1.50, '2024-01-01');

-- GitHub Models (TBD - research phase)
INSERT INTO provider_pricing (provider, model, input_token_price, output_token_price, active_since)
VALUES ('github-models', 'gpt-4', 0.00, 0.00, '2024-01-01')
ON CONFLICT DO NOTHING;

-- =============================================================================
-- VIEWS (convenience queries)
-- =============================================================================

-- Active task runs (not completed/failed/canceled)
CREATE VIEW active_task_runs AS
SELECT * FROM task_runs
WHERE status IN ('queued', 'planning', 'awaiting_approval', 'executing', 'paused')
ORDER BY created_at DESC;

-- Recent token usage summary (last 30 days)
CREATE VIEW recent_token_usage_summary AS
SELECT
    provider,
    model,
    COUNT(*) as request_count,
    SUM(input_tokens) as total_input_tokens,
    SUM(output_tokens) as total_output_tokens,
    SUM(total_tokens) as total_tokens,
    SUM(estimated_cost_usd) as total_cost_usd,
    AVG(estimated_cost_usd) as avg_cost_usd
FROM token_usage
WHERE recorded_at >= NOW() - INTERVAL '30 days'
GROUP BY provider, model
ORDER BY total_cost_usd DESC;

-- Tool call success rate
CREATE VIEW tool_call_success_rate AS
SELECT
    tool_name,
    COUNT(*) as total_calls,
    SUM(CASE WHEN success THEN 1 ELSE 0 END) as successful_calls,
    ROUND(100.0 * SUM(CASE WHEN success THEN 1 ELSE 0 END) / COUNT(*), 2) as success_rate_pct,
    AVG(EXTRACT(EPOCH FROM (ended_at - started_at)) * 1000)::INTEGER as avg_duration_ms
FROM tool_call_records
WHERE started_at >= NOW() - INTERVAL '30 days'
GROUP BY tool_name
ORDER BY total_calls DESC;

-- =============================================================================
-- COMMENTS
-- =============================================================================

COMMENT ON TABLE hosts IS 'Physical/virtual machines, K8s nodes, containers';
COMMENT ON TABLE workloads IS 'Deployments, pods, VMs, LXCs, containers';
COMMENT ON TABLE services IS 'Logical groupings of workloads';
COMMENT ON TABLE tasks IS 'Task templates or one-off task definitions';
COMMENT ON TABLE task_runs IS 'Execution instances of tasks';
COMMENT ON TABLE task_events IS 'Append-only log of task execution events';
COMMENT ON TABLE audit_entries IS 'Immutable audit log for all system actions';
COMMENT ON TABLE token_usage IS 'Denormalized token usage for easy cost tracking';
COMMENT ON TABLE provider_pricing IS 'LLM provider pricing configuration (per 1M tokens)';
